name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install SAM CLI
      - name: Install AWS SAM CLI
        run: |
          sudo pip install aws-sam-cli

      # Step 4: Build SAM Application
      - name: Build SAM Application
        run: sam build

      # Step 5: Deploy SAM Application
      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name sam-app-abdulmaliks \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}
